import { Injectable, Logger } from '@nestjs/common';
import { StorageProvider as StorageProviderName } from '@prisma/client';
import { createHash, createHmac, randomUUID, timingSafeEqual } from 'node:crypto';
import { mkdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, extname, join, resolve, sep } from 'node:path';
import { AppConfig } from '../../../config/config.module';
import {
  ObjectRef,
  SignedUrlOptions,
  StorageProvider,
  StoredObject,
  UploadRequest,
} from '../domain/storage-provider.port';

/** What a valid signature grants access to, and until when. */
export interface LocalDownloadGrant {
  bucket: string;
  objectKey: string;
  expiresAt: number;
}

/**
 * Local-disk storage for development.
 *
 * It is not a mock: files are really written, links really expire, and a
 * tampered signature really fails. The whole upload → entitlement →
 * time-limited download path can therefore be built and tested before any
 * Cloudinary account exists, and switching to Cloudinary later exercises code
 * that was already proven against a working implementation rather than against
 * a stub that always said yes.
 *
 * Env validation refuses to boot production with this driver selected.
 */
@Injectable()
export class LocalStorageAdapter extends StorageProvider {
  readonly name = StorageProviderName.LOCAL;

  private readonly logger = new Logger(LocalStorageAdapter.name);
  private readonly root: string;

  constructor(private readonly config: AppConfig) {
    super();
    this.root = resolve(process.cwd(), this.config.get('STORAGE_LOCAL_ROOT'));
  }

  async upload(request: UploadRequest): Promise<StoredObject> {
    const bucket = this.bucketFor(request.visibility);
    const objectKey = this.buildObjectKey(request);
    const path = this.resolveWithinRoot(bucket, objectKey);

    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, request.content);

    this.logger.debug(`stored ${bucket}/${objectKey} (${request.content.length} bytes)`);

    return {
      provider: this.name,
      bucket,
      objectKey,
      sizeBytes: request.content.length,
      checksumSha256: createHash('sha256').update(request.content).digest('hex'),
      mimeType: request.mimeType,
      originalFilename: request.originalFilename,
    };
  }

  /**
   * Points at this API's own download route. The signature — not the session —
   * is what authorises the fetch, which is exactly how a cloud provider's signed
   * URL behaves, so callers cannot come to depend on a cookie being present.
   */
  getSignedDownloadUrl(ref: ObjectRef, options?: SignedUrlOptions): Promise<string> {
    const ttl = options?.ttlSeconds ?? this.config.get('STORAGE_SIGNED_URL_TTL_SECONDS');
    const expiresAt = Math.floor(Date.now() / 1000) + ttl;

    const params = new URLSearchParams({
      bucket: ref.bucket,
      key: ref.objectKey,
      expires: String(expiresAt),
      signature: this.sign({ bucket: ref.bucket, objectKey: ref.objectKey, expiresAt }),
    });

    if (options?.disposition) params.set('disposition', options.disposition);
    if (options?.downloadFilename) params.set('filename', options.downloadFilename);

    const base = this.config.get('APP_PUBLIC_URL').replace(/\/+$/, '');
    return Promise.resolve(`${base}/storage/local/download?${params.toString()}`);
  }

  async delete(ref: ObjectRef): Promise<void> {
    await rm(this.resolveWithinRoot(ref.bucket, ref.objectKey), { force: true });
  }

  async exists(ref: ObjectRef): Promise<boolean> {
    try {
      await stat(this.resolveWithinRoot(ref.bucket, ref.objectKey));
      return true;
    } catch {
      return false;
    }
  }

  // --- signing ------------------------------------------------------------

  sign(grant: LocalDownloadGrant): string {
    // The separator is a character that cannot appear in a bucket or key, so
    // distinct grants cannot produce the same signing input. Without that,
    // bucket "a/b" + key "c" and bucket "a" + key "b/c" would sign identically.
    return createHmac('sha256', this.config.get('STORAGE_SIGNING_SECRET'))
      .update(`${grant.bucket}\n${grant.objectKey}\n${grant.expiresAt}`)
      .digest('base64url');
  }

  verifySignature(grant: LocalDownloadGrant, signature: string): boolean {
    const expected = Buffer.from(this.sign(grant));
    const actual = Buffer.from(signature);

    // Length must be checked separately: timingSafeEqual throws on a mismatch
    // rather than returning false.
    return expected.length === actual.length && timingSafeEqual(expected, actual);
  }

  // --- paths --------------------------------------------------------------

  /**
   * Resolves under the storage root and proves it stayed there.
   *
   * Keys are generated by this adapter, but on the download path they arrive
   * from a URL. A signature check alone would not help if the signed key itself
   * contained `../` — so containment is enforced structurally here, at the only
   * place that turns a key into a filesystem path.
   */
  resolveWithinRoot(bucket: string, objectKey: string): string {
    const path = resolve(join(this.root, bucket, objectKey));

    if (path !== this.root && !path.startsWith(this.root + sep)) {
      throw new Error('Resolved storage path escapes the storage root');
    }

    return path;
  }

  private bucketFor(visibility: UploadRequest['visibility']): string {
    return visibility === 'PRIVATE'
      ? this.config.get('STORAGE_PRIVATE_BUCKET')
      : this.config.get('STORAGE_PUBLIC_BUCKET');
  }

  /**
   * `<prefix>/<uuid><ext>` — the caller supplies grouping, never the whole key.
   * The UUID makes the key unguessable and collision-free; the original filename
   * is metadata, not part of the path, so a user-supplied name can never steer
   * where bytes land.
   */
  private buildObjectKey(request: UploadRequest): string {
    const extension = extname(request.originalFilename).toLowerCase().slice(0, 12);
    const prefix = (request.keyPrefix ?? '')
      .split('/')
      .map((segment) => segment.replace(/[^a-zA-Z0-9._-]/g, ''))
      .filter(Boolean)
      .join('/');

    const name = `${randomUUID()}${/^\.[a-z0-9]+$/.test(extension) ? extension : ''}`;
    return prefix ? `${prefix}/${name}` : name;
  }
}
